name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission to scripts
        run: chmod +x gradlew .github/decrypt_secrets.sh
      - name: Decrypt GPG secrets
        run: .github/decrypt_secrets.sh
        env:
          SECRETS_GPG_PASS: ${{ secrets.SECRETS_GPG_PASS }}
      - name: Build with Gradle
        run: ./gradlew build connectedCheck --no-daemon
        env:
          KEYSTORE_STORE_PASS: ${{ secrets.KEYSTORE_STORE_PASS }}
          KEYSTORE_KEY_ALIAS: gianlu
          KEYSTORE_KEY_PASS: ${{ secrets.KEYSTORE_KEY_PASS }}